version: '2'

services:
  opensource-contribution-leaderboard:
    build: ./
    volumes:
      - ./src/server/config.json:/dist/server/config.json
      - ./src/assets/data:/data
    ports:
      - "8080:8080"